#!/usr/bin/env python3
"""将 webui 文件转为 C++ 嵌入源码 (src/webui_embedded.cpp)"""
import os
import sys
from pathlib import Path

WEBUI_DIR = Path(__file__).parent
OUTPUT = WEBUI_DIR.parent / "src" / "webui_embedded.cpp"

FILES = [
    ("index.html", "text/html"),
    ("style.css", "text/css"),
    ("app.js", "application/javascript"),
]

def escape_cpp_string(data: str) -> str:
    return (data
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n\"\n\"")
        .replace("\r", ""))

def main():
    entries = []
    for filename, mime in FILES:
        filepath = WEBUI_DIR / filename
        if not filepath.exists():
            print(f"WARNING: {filepath} not found, skipping")
            continue
        content = filepath.read_text(encoding="utf-8")
        escaped = escape_cpp_string(content)
        entries.append((filename, mime, escaped))

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write('// AUTO-GENERATED by webui/embed.py - DO NOT EDIT\n')
        f.write('#include <httplib.h>\n')
        f.write('#include <string>\n')
        f.write('#include <unordered_map>\n\n')

        f.write('namespace webui_embedded {\n\n')

        f.write('struct EmbeddedFile {\n')
        f.write('    const char* content;\n')
        f.write('    size_t size;\n')
        f.write('    const char* content_type;\n')
        f.write('};\n\n')

        for filename, mime, escaped in entries:
            varname = filename.replace(".", "_").replace("-", "_")
            f.write(f'static const std::string data_{varname} =\n')
            f.write(f'"{escaped}";\n\n')

        f.write('static const std::unordered_map<std::string, EmbeddedFile> files = {\n')
        for filename, mime, _ in entries:
            varname = filename.replace(".", "_").replace("-", "_")
            f.write(f'    {{"{filename}", {{data_{varname}.c_str(), data_{varname}.size(), "{mime}"}}}},\n')
        f.write('};\n\n')

        f.write('void mount(httplib::Server& server) {\n')
        f.write('    for (const auto& [name, file] : files) {\n')
        f.write('        std::string path = "/ui/" + name;\n')
        f.write('        server.Get(path, [&file](const httplib::Request&, httplib::Response& res) {\n')
        f.write('            res.set_content(file.content, file.size, file.content_type);\n')
        f.write('        });\n')
        f.write('    }\n')
        f.write('    // /ui -> /ui/index.html\n')
        f.write('    server.Get("/ui", [](const httplib::Request&, httplib::Response& res) {\n')
        f.write('        res.set_redirect("/ui/index.html");\n')
        f.write('    });\n')
        f.write('    server.Get("/ui/", [](const httplib::Request&, httplib::Response& res) {\n')
        f.write('        res.set_redirect("/ui/index.html");\n')
        f.write('    });\n')
        f.write('}\n\n')

        f.write('} // namespace webui_embedded\n')

    print(f"Generated: {OUTPUT} ({OUTPUT.stat().st_size} bytes)")

if __name__ == "__main__":
    main()
